### ISSUE TITLE
android:exposed = True for com.google.firebase.iid.FirebaseInstanceIdService

### ISSUE THREAD

**Issue by deed02392** [dandar3/android-google-firebase-iid#1]
https://github.com/dandar3/android-google-firebase-iid/blob/master/AndroidManifest.xml#L40

The comment suggests this is not a security issue because the service does security checks. Is there a reference for this?

**Comment by dandar3** [comment]
I can't see any particular reference in the Firebase documentation:
https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService

We can send a comment directly on the page through the `Submit Button` (top right corner) so they add more details on the security check itself.

Might be worth changing to `False` and see if functionality you use still works.

Have tried decompiling the source with JDGUI and it failed with `Internal Error' unfortunately.

**Comment by deed02392** [comment]
I couldn't either, and thanks for looking too.

I've asked this on the [security SE](https://security.stackexchange.com/questions/180996/is-it-safe-to-expose-these-particular-firebase-derived-services), if we track it over there someone clever and/or with access to source if we're lucky might respond. 

But I don't think this is an issue related to your project necessarily so I will close it now.
